### ISSUE TITLE
Support elasticsearch-java-client

### ISSUE THREAD

**Issue by HendrikWeiss** [senacor/elasticsearch-evolution#109]
As of Elasticsearch 7.15, the old `RestHighLevelClient` is deprecated in favor of the new [API client](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/index.html). This change should also be made in elasticsearch-evolution, but before I start creating a PR, I would like to clarify the best way of going forward.

The two major options I see are:

## Keep Support for the old client

From a user perspective, this is the favourable approach. We'd keep supporting the `RestHighLevelClient`, possibly marking it as deprecated.
The main issues with that approach would be the more complicated test logic, especially with covering over multiple elasticsearch versions and that users who use the library with elasticsearch versions lower than 7.15 would still be subjected to the deprecation warnings.

## Drop Support for the old client

This would be a clean cut, dropping support for the `HighLevelRestClient` and by extension, all elasticsearch versions that do not support the newer client. While potentially excluding users from the newer versions of elasticsearch-evolution, this would keep the implementation and verification simpler.

Do you have any thoughts on which of these options seem preferable?

**Comment by siehlema** [comment]
The current use of the `RestHighLevelClient` also leads to `ignore_throttled` warnings during the migration.

**Comment by michaelriedel** [comment]
One of the main benefits of the new client is the fact that it no longer depends on the whole Elasticsearch server, and thus our build artifacts would be significantly smaller with the new client (but only if we dropped the old RestHighLevelClient). So I definitely vote for the clean cut. 
People still using old Elasticsearch versions will still be able to use the existing versions of elasticsearch-evolution without any drawbacks...

**Comment by S1riU5** [comment]
I would also vote for Drop Support for the old client

**Comment by xtermi2** [comment]
I will suggest here another Option:
## Migrate to LowLevelClient and keep support for old versions.

Maybe it would be the best to do the request "manually" via LowLevelClient `RestClient`. There are only 8 requests, and one of them will be migrated to the LowLevelClient with [#118](https://github.com/senacor/elasticsearch-evolution/pull/118). The requests are not that complicated to really strongly benefit from the "High Level" clients.
Maybe even 8.x will be easy to support and OpenSearch also.

**Comment by michaelriedel** [comment]
@xtermi2, your solution removes the Elastic server dependency, too. But be aware that we lose the 'feature' of getting compile errors on future breaking Elastic API changes. A hybrid approach (using the low-level client for old Elastic version and the new Java client for newer versions) might be better...

**Comment by xtermi2** [comment]
> @xtermi2, your solution removes the Elastic server dependency, too. But be aware that we lose the 'feature' of getting compile errors on future breaking Elastic API changes. A hybrid approach (using the low-level client for old Elastic version and the new Java client for newer versions) might be better...

Elasticsearch Evolution has good integration tests for all ES versions - breaking changes should be detected that way.
A hybrid approach is in my opinion the worst option - maintaining both variants is much effort. 
Elasticsearch Evolution uses only a couple of APIs:
* search (findAll)
* index (saveOrUpdate)
* count (isLocked / lock)
* updateByQuery (lock / unlock)
with easy queries/requests - so a breaking API change affecting Elasticsearch Evolution has a really low change.

**Comment by xtermi2** [comment]
With release [0.4.0](https://github.com/senacor/elasticsearch-evolution/releases/tag/0.4.0-2022-04-03T14-09-23-e34532a) I've removed the RestHighLevelClient dependency in production code and replaced with LowLevelClient. 
As expected, supporting Elasticsearch 8 and Opensearch, was quite easy with that approach :tada:

:arrow_right:  I will close this issue.
