### ISSUE TITLE
Unable to proceed with elasticsearch-evolution on aws elasticsearch

### ISSUE THREAD

**Issue by ttj4** [senacor/elasticsearch-evolution#114]
Not sure if this would be an issue with this library, to begin with. 

I'm on AWS ES 7.10 and using a high-level rest client with 7.10 version as well (I'm on Java 8). While trying to run the template schema migration I see the following error :

```
curl -iX POST 'https://some-domain-name.us-east-1.es.amazonaws.com/es_evolution/_refresh?ignore_throttled=false&ignore_unavailable=true&expand_wildcards=open&allow_no_indices=true'
# HTTP/1.1 403 Forbidden
# Date: Mon, 21 Mar 2022 14:33:12 GMT
# Content-Type: application/json
# Content-Length: 192
# Connection: keep-alive
# x-amzn-RequestId: abcdef-ghij-klmno-pqrstu-vwxuyz
# Access-Control-Allow-Origin: *
#
# {"message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}
```

But I could see the following request as well which returns a success.
```
 | 2022-03-21 | 14:33:10.793 | main | TRACE | (RequestLogger.java:logResponse:83) | curl -iX HEAD 'https://some-domain-name.us-east-1.es.amazonaws.com/es_evolution'
# HTTP/1.1 200 OK
# Date: Mon, 21 Mar 2022 14:33:10 GMT
# Content-Type: application/json; charset=UTF-8
# Content-Length: 243
# Connection: keep-alive
# Access-Control-Allow-Origin: *

```

I'm not sure what is going on here. Any help would be appreciated 
Thank you!

**Comment by xtermi2** [comment]
Looks like your user is not allowed to do this "refresh" call. Do you use the "elastic" (admin) user, with all privileges or a manually created user with restricted privileges?

Before the first refresh happens the index is checked for existence, this is the HEAD call you mentioned, then the index will be created if it does not exist `PUT /es_evolution`. 

Then the first "refresh" `POST /es_evolution/_refresh?ignore_throttled=false&ignore_unavailable=true&expand_wildcards=open&allow_no_indices=true` is done.
I never tested Elasticsearch Evolution on AWS Elasticserach Service, but this call is nothing special.

**Comment by ttj4** [comment]
I have given the full permission for testing this out. I do see similar issues being opened with aws 
https://github.com/aws/aws-sdk-java/issues/2205

**Comment by xtermi2** [comment]
Ok, sounds like this will only happen on `POST` requests with empty body. Can you try, if a `GET /es_evolution/_refresh?ignore_throttled=false&ignore_unavailable=true&expand_wildcards=open&allow_no_indices=true` is working on AWS Elastic search Service?

**Comment by ttj4** [comment]
yes with GET it does work. Can I raise a PR for this?

**Comment by xtermi2** [comment]
Yes, then you have to do the request without RestHighLevelClient (`restHighLevelClient.getLowLevelClient().performRequest(...)`) in `HistoryRepositoryImpl` in method `void refresh(String... indices)`. In this class is already another example of a request with the LowLevelClient.

**Comment by ttj4** [comment]
@xtermi2 here's the PR : https://github.com/senacor/elasticsearch-evolution/pull/118
I haven't updated the versions though. Let me know your thoughts
