### ISSUE TITLE
Issue with Java 11, spring boot 2.2/2.3 and org.reflections:reflections:0.9.11

### ISSUE THREAD

**Issue by nilskuhn** [senacor/elasticsearch-evolution#13]
Hi there, 

we were hitting [this bug](https://github.com/ronmamo/reflections/issues/279) running version 0.3.0. It happens because of a bug in Spring Boot in combination with Java 11 and version 0.9.12 of the following dependency 
```
<dependency>
  <groupId>org.reflections</groupId>
  <artifactId>reflections</artifactId>
  <version>0.9.12</version>
</dependency> 
```
Locally everything worked, running app from IntelliJ, but deployed to openshift, running inside a container using image `openjdk:11.0.4-jre-slim` Spring Boot application failed to start throwing `java.lang.IllegalStateException: zip file closed`.

Fortunately [release 2.3.6](https://github.com/spring-projects/spring-boot/releases/tag/v2.3.6.RELEASE) of Spring Boot fixes this bug, but it seams to fail with versions 2.3.4 and 2.3.5. We were able to update to Sping version 2.3.6, so fine for us, but maybe it would be helpful for others if you point out this limitation in README. I think it would also be able to downgrade reflections to version 0.9.11 to support Spring versions 2.3.4 and 2.3.5, but probably it is not worth the effort.

Regards, Nils

**Comment by xtermi2** [comment]
Thx to point this out.
We had the same issue at work with org.reflections some weeks ago and removed this dependency completely and used spring functionality to scan for annotations in our classpath.
But here this is not that easy, because evolution-core has no spring dependency and will not get one.
Now, that this is fixed in spring-boot 2.3.6 it's not really a issue.

**Comment by xtermi2** [comment]
docu updated

**Comment by xtermi2** [comment]
Link to spring-boot issue: https://github.com/spring-projects/spring-boot/issues/23821
