### ISSUE TITLE
Detect modified migration scripts

### ISSUE THREAD

**Issue by felixkrull-neuland** [senacor/elasticsearch-evolution#155]
When comparing the local migration scripts with the record of already the executed scripts, the library should be able to detect if an already-executed script was modified afterwards, and raise an error. Given that checksums of the scripts are calculated and stored, I was surprised that this wasn't already being checked. I'm not that familiar with Flyway, but [the Play Framework's evolutions module](https://www.playframework.com/documentation/2.8.x/Evolutions#Inconsistent-states) does verify the checksum.

Is this an intentional design choice? If not, I'd change it and open a PR.

**Comment by xtermi2** [comment]
fixed with [v0.4.1](https://github.com/senacor/elasticsearch-evolution/releases/tag/0.4.1-2023-01-11T21-25-03-c534c02)
