### ISSUE TITLE
Add the baseline feature

### ISSUE THREAD

**Issue by larochef** [senacor/elasticsearch-evolution#164]
In flyway, there is a feature to set a baseline.
For instance, if you set the baseline to V2, then all the V1 scripts will not be run, and teh migrations will start with the V2_0 script.

The use case for this is when you have environment with existing data and other ones (like the local env) with nothing. You'll was to run the index creations in dev but not on an existing environment where it will fail.

Is it a feature you would accept?

**Comment by xtermi2** [comment]
Hi @larochef 

I know this flyway feature, I have already used it.
Yes, I will accept this. Just use flyway as a guide when naming the configuration in your PR.

**Comment by larochef** [comment]
Created #167 for it
