### ISSUE TITLE
release 0.4.1?

### ISSUE THREAD

**Issue by larochef** [senacor/elasticsearch-evolution#168]
Hello all,

I wouldn't want to be too pushy, but I would need the baseline feature in the projects I have to really start using elasticsearch-evolution, do you think it is something you could do soon?

**Comment by maaaNu** [comment]
@xtermi2 Can you help us out?

**Comment by xtermi2** [comment]
Release is coming today if everything is going well

**Comment by larochef** [comment]
Great, thx !
