### ISSUE TITLE
Checksum for parsed scripts depends on the system's line ending

### ISSUE THREAD

**Issue by felixkrull-neuland** [senacor/elasticsearch-evolution#182]
Currently migration scripts are read by splitting them into lines and then rejoining those lines using the system line separator ([MigrationScriptReaderImpl.java:165](https://github.com/senacor/elasticsearch-evolution/blob/master/elasticsearch-evolution-core/src/main/java/com/senacor/elasticsearch/evolution/core/internal/migration/input/MigrationScriptReaderImpl.java#L165)). The checksum for the script is calculated based on the rejoined text.

This means the checksum depends on the line ending setting of the system: applying the same script on a Windows and a Linux system will lead to different checksums being stored and mixing them will lead to checksum conflict errors (if enabled). It's not even possible to circumvent this problem by changing the line endings of the file on disk since those are immediately discarded.

**Comment by xtermi2** [comment]
I expect this is more a shared dev environment problem, right, not a production issue?
@felixkrull-neuland is this solution suitable for you: #183 
Then I would release a new version in the next days.
