### ISSUE TITLE
Dependency update of org.reflections

### ISSUE THREAD

**Issue by RiVogel** [senacor/elasticsearch-evolution#235]
Hi @xtermi2, thanks for this cool library!

We tried to integrate it in our project but sadly we are not able to downgrade org.reflections:reflections to a 0.9.x version.

I already saw your effort in https://github.com/ronmamo/reflections/issues/391 to solve this update, but long time no answer...

Please consider my PR https://github.com/senacor/elasticsearch-evolution/pull/233 to fix this dependency problem. Sadly I did not find a solution which is compatible to reflections version 0.9.x AND 0.10.x.

Regards

**Comment by xtermi2** [comment]
thanks @RiVogel, looks promising :)

**Comment by xtermi2** [comment]
released in [v0.4.3](https://github.com/senacor/elasticsearch-evolution/releases/tag/0.4.3-2023-11-13T22-53-52-9018898)
