### ISSUE TITLE
Compatibility to AWS OpenSearch

### ISSUE THREAD

**Issue by RiVogel** [senacor/elasticsearch-evolution#236]
Hi @xtermi2,

do you have experience if and how to use elasticsearch-evolution within the AWS ecosystem?

I guess the main issue will be to adapt the AWS request signing within the elasticsearch RestClient.

**Comment by xtermi2** [comment]
No Sorry. This is the fisrt time I hear that AWS OpenSearch Service is requireing request signing.
Last time I used AWS OpenSearch Service was with version 1.x and when I remember right this was just working out of the box.
Are you using IAM to authenticate? I was using just the OpenSearch user/PW without IAM.

**Comment by RiVogel** [comment]
Sorry for my late reply. Yes, I am connecting OpenSearch via IAM. But we got it to work by just using the Aws4Signer within a request interceptor.

**Comment by ysfaran** [comment]
@RiVogel I also use IAM for authentication. Could you share how you exactly implemented the interceptor with Aws4Signer?
