### ISSUE TITLE
Spring boot ElasticsearchRestClientAutoConfiguration is shaded by ElasticsearchEvolutionAutoConfiguration

### ISSUE THREAD

**Issue by ivan-bezyazychnyy** [senacor/elasticsearch-evolution#29]
As I can see the spring boot's `ElasticsearchRestClientAutoConfiguration` might happen after `ElasticsearchEvolutionAutoConfiguration`.
I see that `ElasticsearchEvolutionAutoConfiguration` contains the code:
```
@AutoConfigureAfter(name = {
        "org.springframework.boot.autoconfigure.elasticsearch.rest.RestClientAutoConfiguration" // since spring-boot 2.1
})
```
But I do not see the `org.springframework.boot.autoconfigure.elasticsearch.rest.RestClientAutoConfiguration` and I see `org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration` in spring boot 2.4.3. May be it was replaced?
As a result the `RestHighLevelClient` is configured by `elasticsearch-evolution` and some configuration parameters like `spring.elasticsearch.rest.username` are not supported.
I suggest to add extra line into `@AutoConfigureAfter`.

**Comment by xtermi2** [comment]
Yes, you are totally right. It should look like this:
```java
@AutoConfigureAfter(name = {
        "org.springframework.boot.autoconfigure.elasticsearch.rest.RestClientAutoConfiguration", // spring-boot 2.1 / 2.2
        "org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration" // spring-boot 2.3+
})
```
Will be fixed soon ;)

**Comment by ivan-bezyazychnyy** [comment]
@xtermi2 Thanks for the fast fix! Could you please say when to expect the next release with this fix? It would be great to understand it so we can decide to wait for it or we will have to make our own build.

**Comment by xtermi2** [comment]
@ivan-bezyazychnyy  The release `0.3.1` will be out in the next couple of hours :rocket:

**Comment by ivan-bezyazychnyy** [comment]
@xtermi2 Thank you!
