### ISSUE TITLE
Error using bulk operation 

### ISSUE THREAD

**Issue by yphinera** [senacor/elasticsearch-evolution#293]
When we execute a bulk script : 
![image](https://github.com/senacor/elasticsearch-evolution/assets/59996426/fe767918-eece-4044-b5e4-e473bb393448)

we got this error :  
Caused by: org.elasticsearch.client.ResponseException: method [POST], host [http://localhost:9200], URI [_bulk], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The bulk request must be terminated by a newline [\\n]"}],"type":"illegal_argument_exception","reason":"The bulk request must be terminated by a newline [\\n]"},"status":400}

while elasticsearch bulk api require a newline character \n
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html
![image](https://github.com/senacor/elasticsearch-evolution/assets/59996426/2a41e5e5-ecff-433b-95b8-2b9ecd1f76b4)

It seems elasticsearch-evolution lost the new line newline character
![image](https://github.com/senacor/elasticsearch-evolution/assets/59996426/9ec61d60-7e6a-475c-b479-c758d37276dc)

Could you fix it plz ?

Thanks in advance

**Comment by xtermi2** [comment]
Thank @yphinera for reporting this bug. 
I hope I can provide you at the weekend with a fixed version.

**Comment by xtermi2** [comment]
@yphinera can you please try out the pull request #294 
you can build elasticsearch-evolution via ` ./mvnw clean install -DskipTests=true` and set version to `0.5.2-SNAPSHOT` in your application.

**Comment by yphinera** [comment]
Hi @xtermi2 you were so fast ! Thanks a lot, the code looks good and the fix works well 👍. The issue is resolve for me.
