### ISSUE TITLE
Checksum changes for existing migration scripts since release 0.5.2

### ISSUE THREAD

**Issue by lennehendrickx** [senacor/elasticsearch-evolution#298]
We have issue with checksums which have changed since 0.5.2 for existing migration scripts.

**Example script**

```
PUT /channel_1_es7
Content-Type: application/json

{
  "aliases": {
    "channel": {}
  },
  "settings": {
    "index": {
      "number_of_shards": 1
    },
    "refresh_interval": "30s",
    "default_pipeline": "ingestion-pipeline"
  },
  "mappings": {
    "dynamic": "strict",
    "properties": {
      "channelDisplayName": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      },
      "channelId": {
        "type": "keyword"
      },
      "channelName": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      },
      "createdAt": {
        "type": "date",
        "format": "date_optional_time"
      },
      "ingestedAt": {
        "type": "date",
        "format": "date_optional_time"
      },
      "mediumChannelId": {
        "type": "keyword"
      },
      "mediumId": {
        "type": "keyword"
      },
      "organizationId": {
        "type": "long"
      },
      "testChannel": {
        "type": "boolean"
      },
      "updatedAt": {
        "type": "date",
        "format": "date_optional_time"
      }
    }
  }
}

```

**Checksum**
- before 0.5.2: 1754437828
- since 0.5.2: -1447002170

Note that the migration script has a trailing newline. 
Could this issue be triggered by the changes made in this commit? [3d80bc4ae448f588267e4b9edb9ab954409441e8](https://github.com/senacor/elasticsearch-evolution/commit/3d80bc4ae448f588267e4b9edb9ab954409441e8)?

**Comment by xtermi2** [comment]
Hi @lennehendrickx 
yes, this is related to this commit, respectively #293 / #294
This was a bug, before all trailing newlines were removed.

Let me try if I can calculate the checksume with removed trailing newlines.
When this works, I would provide a property to configure this "legacy" checksum calculation

**Comment by xtermi2** [comment]
@lennehendrickx can you please try out the pull request https://github.com/senacor/elasticsearch-evolution/pull/299
you can build elasticsearch-evolution via  ./mvnw clean install -DskipTests=true and set version to 0.6.0-SNAPSHOT in your application.

**Comment by lennehendrickx** [comment]
Hi @xtermi2 ,

Thanks for your quick fix.
I was able to verify that the new config flag `trimTrailingNewlineInMigrations` works as expected.
With the snapshot version and the flag enabled, I now get the old checksum.
