### ISSUE TITLE
Auto reindex 

### ISSUE THREAD

**Issue by arcturuscom** [senacor/elasticsearch-evolution#49]
Hello, 
I'm asking if its possible to auto reindex after mapping update.

**Comment by xtermi2** [comment]
Hi @arcturuscom,

that's not part of the concept how elelasticsearch-evolution is designed. 
You can easily do a reindex request if necessary as part of a migration.

Elasticsearch-evolution is not aware of your Elasticsearch structure, e.g. what indices exist or which should be reindexed.
It's not planed to implement a feature like that.
