### ISSUE TITLE
Can't get this to work with ES version 7.6.2

### ISSUE THREAD

**Issue by nilskuhn** [senacor/elasticsearch-evolution#5]
I am trying to use this in a spring boot project and am facing some version incompatibilities with elasticsearch client.

pom.xml:
```
...
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.4.RELEASE</version>
        <relativePath/>
    </parent>
...
    <dependencies>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-elasticsearch</artifactId>
            # spring-boot parent provides version 7.6.2
        </dependency>
        <dependency>
            <groupId>com.senacor.elasticsearch.evolution</groupId>
            <artifactId>spring-boot-starter-elasticsearch-evolution</artifactId>
            <version>0.2.0</version>
        </dependency>
    </dependencies>
```
Starting the application with some migration scripts in place, I am getting the following:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.senacor.elasticsearch.evolution.core.internal.migration.execution.MigrationServiceImpl.executeScript(MigrationServiceImpl.java:122)

The following method did not exist:

    'void org.elasticsearch.client.RequestOptions$Builder.addHeader(java.lang.String, java.lang.String)'

The method's class, org.elasticsearch.client.RequestOptions$Builder, is available from the following locations:

    jar:file:/home/nkuhn/.m2/repository/org/elasticsearch/client/elasticsearch-rest-client/7.6.2/elasticsearch-rest-client-7.6.2.jar!/org/elasticsearch/client/RequestOptions$Builder.class

The class hierarchy was loaded from the following locations:

    org.elasticsearch.client.RequestOptions.Builder: file:/home/nkuhn/.m2/repository/org/elasticsearch/client/elasticsearch-rest-client/7.6.2/elasticsearch-rest-client-7.6.2.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of org.elasticsearch.client.RequestOptions$Builder
```

Already tried to set elastic version explicitly:

```
<properties>
    <elasticsearch.version>7.6.2</elasticsearch.version>
</properties>
```
Same result.

Also tried to exclude elasticsearch client lib explicitly:

```
        <dependency>
            <groupId>com.senacor.elasticsearch.evolution</groupId>
            <artifactId>spring-boot-starter-elasticsearch-evolution</artifactId>
            <version>0.2.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.elasticsearch.client</groupId>
                    <artifactId>elasticsearch-rest-client</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.elasticsearch.client</groupId>
                    <artifactId>elasticsearch-rest-high-level-client</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.elasticsearch.client</groupId>
                    <artifactId>transport</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
No effect.

Any ideas, how to solve this? 
Seams like version 7.6.2 should be supported.

**Comment by S1riU5** [comment]
Hey @nilskuhn,
can you provide a repo with a non working example. I tried to reproduce the mentioned issue but couldn't.

cheers

**Comment by S1riU5** [comment]
Hey @nilskuhn,
I could reproduce the issue now, i was on the wrong rest-high-level-client version. No need for a repo link. I'll look into it a

**Comment by S1riU5** [comment]
Now i was able to reproduce the issue. I was on the wrong rest-high-level-client version, sorry. Will look into it.

cheers

**Comment by S1riU5** [comment]
Hey, @nilskuhn 
can you verify if it works if you change
`<elasticsearch.version>7.6.2</elasticsearch.version>` to `<elasticsearch.version>7.3.2</elasticsearch.version>`

**Comment by nilskuhn** [comment]
Yes, with `<elasticsearch.version>7.3.2</elasticsearch.version>` it works!
Thanks, I would use that version until you are providing a fix for version 7.6.2.
We are planing to update to latest ES version 7.9 soon. Do you plan to test / support latest versions in the future?

**Comment by S1riU5** [comment]
Hey @nilskuhn,
Yes, I'll look into it and fix it as soon as possible. We also have to migrate to 7.9, So I will create PR to support the newest version.

**Comment by nilskuhn** [comment]
Thanks a lot!
And, I forgot to mention: Great that you published this project! 
Using ES as an application backing database, storing some domain objects (which is maybe not exactly what ES is supposed to be used for), aside [this](https://github.com/hubrick/elasticsearch-migration) small tool I didn't find other solutions.

**Comment by nilskuhn** [comment]
Unfortunately, I can't go with `<elasticsearch.version>7.3.2</elasticsearch.version>` because than, I am running into [this kind of errors](https://www.programmersought.com/article/82574260480/) due to multiple versions of elasticsearch-rest-high-level-client dependency at runtime :(

So I will have to wait for a fix for version 7.6.2. Please let me know, if I may help with something to get the fix done.

**Comment by S1riU5** [comment]
Okay, then I'll try to find a good solution. I'll contact you as soon as I found a good one.

**Comment by xtermi2** [comment]
I've updated some versions and added Elasticsearch 7.8 and 7.9 compatibility tests. Maybe this helps.
@S1riU5 If you need support with this issue just contact me on WhatsApp

**Comment by xtermi2** [comment]
Ah, another idea:
```
<elasticsearch.version>6.8.6</elasticsearch.version>
```
This is what elasticsearch-evolution uses internal. This is definitive compatible with Elasticsearch  "7.9.3", "7.8.1", "7.7.1", "7.6.2", "7.5.2", "7.4.2", "7.3.2", "7.2.1", "7.1.1", "7.0.1" and "6.8.13"
But don't use a higher 6.8 version, because we have documented there some issues:
> es client 6.8.7/6.8.8/6.8.9/6.8.10/6.8.11/6.8.12/6.8.13 does not work with ES 7.6.2, 7.5.2 and 7.4.2 so keep 6.8.6 until this issue is fixed

**Comment by S1riU5** [comment]
Maybe that can work... I created  #6 to increase the internally used es-rest-client-versions. Not sure if this is the best solution.

**Comment by nilskuhn** [comment]
Please let me know, if it makes sense, to test it.

**Comment by nilskuhn** [comment]
> Ah, another idea:
> 
> ```
> <elasticsearch.version>6.8.6</elasticsearch.version>
> ```
> ...

As I mentioned earlier in this thread, this doesn't work because of two different versions of elasticsearch, one of evolution and another one of my own spring application:
> I am running into [this kind of errors](https://www.programmersought.com/article/82574260480/) due to multiple versions of elasticsearch-rest-high-level-client dependency at runtime :(

**Comment by nilskuhn** [comment]
@S1riU5 Could you check PR of @xtermi2 ? There are some tests failing.
I would really like to use evolution, but at the moment it doesn't work using ES version 7.6.2 in productive Spring application.

**Comment by xtermi2** [comment]
@S1riU5 is working on this issue in #6 and will cut Elasticsearch compatibility to 7.5.0+ in release 0.3.0
But please be patient, we are working on this project in our spare time.

**Comment by nilskuhn** [comment]
Ok, sorry for being so pushy, from your last comments I could not see if you are still actively working on this topic.
Take your time and thanks.

**Comment by xtermi2** [comment]
@nilskuhn can you please verify the 0.3.0-SNAPSHOT release with this maven snapshot repository:
```
	<repositories>
		<repository>
			<id>ossrh</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
		</repository>
	</repositories>
```

**Comment by nilskuhn** [comment]
NICE, works for me with `<elasticsearch.version>7.6.2</elasticsearch.version>`.
Thanks!

**Comment by nilskuhn** [comment]
You are mentioning in the README, elasticsearch-evolution >= 0.3.0 works with ES versions 7.5.x and later. Does this already cover latest ES version 7.9?

**Comment by xtermi2** [comment]
Nice, then I will release this SNAPSHOT under `0.3.0`

> You are mentioning in the README, elasticsearch-evolution >= 0.3.0 works with ES versions 7.5.x and later. Does this already cover latest ES version 7.9?

yes, 7.9.x and 7.10.x
