### ISSUE TITLE
The reindex data loss

### ISSUE THREAD

**Issue by isfong** [senacor/elasticsearch-evolution#63]
Thank you so much for sharing this library, I want to use it to achieve the reindex, but can not succeed, but lost my document data.
### My choreography steps:
* the raw index has a data doc
`create_a_new_snapshot_index` -> `reindex_raw_index_to_snapshot_index` -> `delete_raw_index` -> `create_raw_index` -> `reindex_snapshot_index_to_raw_index` -> `delete_snapshot_index` -> `done`
* the raw index loss all data doc
## [This is my migration files](https://github.com/senacor/elasticsearch-evolution/files/6746615/migration.zip)
* I use curl to verify that I can do what I expect and don't lose data

**Comment by S1riU5** [comment]
Hey @isfong 
can you please provide some details like 
* elasticsearch version 
* rest high level client version
* evolution version
* evolution execution logs
* a additional script or curl request to create at least one document

That would be helpful. 
I can look into the issue on weekend.

cheers
@S1riU5

**Comment by isfong** [comment]
> Hey @isfong
> can you please provide some details like
> 
> * elasticsearch version
> * rest high level client version
> * evolution version
> * evolution execution logs
> * a additional script or curl request to create at least one document
> 
> That would be helpful.
> I can look into the issue on weekend.
> 
> cheers
> @S1riU5

This is the simple SpringBoot project I tested: [elasticsearch-evolution-simple.zip](https://github.com/senacor/elasticsearch-evolution/files/6774023/elasticsearch-evolution-simple.zip)  
These are my information
* OS: MacOS BigSu 11.4
* Elasticsearch version: docker.io/elasticsearch:7.12.1
* Evolution version: com.senacor.elasticsearch.evolution:spring-boot-starter-elasticsearch-evolution:0.3.2

### Start the elasticsearch service

```shell
docker-compose up
```

### `application.properties`

```properties
spring.elasticsearch.evolution.locations[0]=classpath:es/nothing
#spring.elasticsearch.evolution.locations[0]=classpath:es/migration
```

### POST `/books`

```shell
curl -X 'POST' \
  'localhost:8080/books' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
        "name": "Microservices Patterns",
        "author": "Chris Richardson"
      }'
```

```json
{
  "bookId": "6eec24cc77844b60af9048ba39c6a597"
}
```

### GET `/books`

```shell
curl 'localhost:8080/books' \
  -H 'accept: application/json'
```

```json
{
  "id": "6eec24cc77844b60af9048ba39c6a597",
  "name": "Microservices Patterns",
  "author": "Chris Richardson"
}
```

### The raw mapping

`curl localhost:9200/book/_mapping`

```json
{
  "book": {
    "mappings": {
      "properties": {
        "_class": {
          "type": "keyword",
          "index": false,
          "doc_values": false
        },
        "author": {
          "type": "keyword"
        },
        "id": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "name": {
          "type": "keyword"
        }
      }
    }
  }
}
```

### Allow the `application.properties` migration and restart the app server
The [V1.0.3__create_book_new_index.http](src/main/resources/es/migration/V1.0.3__create_book_new_index.http) Corresponding to Java file modifications
```java
public class Book {
    @Id
    private String id;
    // @Field( type = FieldType.Keyword )
    @Field( type = FieldType.Text ) // Change to text
    private String name;
    @Field( type = FieldType.Keyword )
    private String author;
}
```

```properties
#spring.elasticsearch.evolution.locations[0]=classpath:es/nothing
spring.elasticsearch.evolution.locations[0]=classpath:es/migration
```

### Now the document data is loss
```shell
curl 'localhost:8080/books' \
  -H 'accept: application/json'
```

```json
[]
```

I used the IDEA to manually execute http request the migration files and reproduce the above steps, and the data is preserved  
Did I make a mistake? Please correct me, thanks!

**Comment by S1riU5** [comment]
Hey @isfong,
I think you can fix the problem by adding the ?refresh parameter to your reindex request. I tested the scripts and it seem to work on my side can you verify it please ?
[migration.zip](https://github.com/senacor/elasticsearch-evolution/files/6796780/migration.zip)

**Comment by S1riU5** [comment]
Hey @isfong 
I'll close the issue feel free to open a new one if you face any other issues.
